services:
  sabc-ui:
    container_name: submit-a-bulk-claim-app
    profiles:
      - application
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_SOURCE=internal
      secrets:
        - github_actor
        - github_token
    environment:
      SERVER_MAX_FILE_SIZE: 50MB
      UPLOAD_MAX_FILE_SIZE: 10MB
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      AUTH_SCOPE: ${AUTH_SCOPE}
      AUTH_TENANT_ID: ${AUTH_TENANT_ID}
      SDS_API_URL: ${SDS_API_URL}
      CLAIM_API_URL: http://claims-api:8080
      CLAIMS_API_ACCESS_TOKEN: f67f968e-b479-4e61-b66e-f57984931e56
      REST_CLIENT_CONNECT_TIMEOUT: ${REST_CLIENT_CONNECT_TIMEOUT:-5000}
      REST_CLIENT_READ_TIMEOUT: ${REST_CLIENT_READ_TIMEOUT:-40000}
      REDIS_HOST: redis://redis:6379
      SPRING_PROFILES_ACTIVE: ${SUBMIT_SPRING_PROFILES_ACTIVE:-oidc}
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      IS_NIL_SUBMISSION_ENABLED: true
      IS_ALTERNATIVE_CLAIM_VIEW_ENABLED: true
    # Information on why these ports here: https://github.com/ministryofjustice/laa-data-claims-parent#exposed-ports
    ports:
      - "8082:8082"
      - "8182:8081"
      - "5082:5005"
    depends_on:
      - redis

  claim-service:
    image: wiremock/wiremock:latest
    container_name: claim-service
    entrypoint:
      [
        "/docker-entrypoint.sh",
        "--global-response-templating",
        "--disable-gzip",
        "--verbose",
      ]
    volumes:
      - ./wiremock/mappings/claim-service:/home/wiremock/mappings
    restart: always
    ports:
      - "8091:8080"

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: always
    ports:
      - "6382:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
