server:
  tomcat:
    max-swallow-size: 500MB
  port: 8082

spring:
  application:
    name: laa-submit-a-bulk-claim
  servlet:
    multipart:
      max-file-size: ${SERVER_MAX_FILE_SIZE}
      max-request-size: ${SERVER_MAX_FILE_SIZE}
  security:
    oauth2:
      client:
        registration:
          silas-identity:
            client-id: ${SILAS_CLIENT_ID}
            client-secret: ${SILAS_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: ${SILAS_SCOPE}
          moj-identity:
            client-id: ${AUTH_CLIENT_ID}
            client-secret: ${AUTH_CLIENT_SECRET}
            scope: ${AUTH_SCOPE}
            authorization-grant-type: client_credentials
        provider:
          silas-identity:
            # user-name-attribute: email
            issuer-uri: https://login.microsoftonline.com/${SILAS_TENANT_ID}/v2.0
          moj-identity:
            issuer-uri: https://login.microsoftonline.com/${AUTH_TENANT_ID}/v2.0
  threads:
    virtual:
      enabled: true
  http:
    client:
      factory: jdk
      connect-timeout: ${REST_CLIENT_CONNECT_TIMEOUT:5000}
      read-timeout: ${REST_CLIENT_READ_TIMEOUT:40000}
  session:
    store-type: redis

  data:
    redis:
      url: ${REDIS_HOST}

security:
  allowed-hosts: ${ALLOWED_HOSTS:localhost,localhost:8082,127.0.0.1,127.0.0.1:8082}
app:
  canonical-base-url: ${CANONICAL_BASE_URL:http://localhost:8082}
  landing:
    deadline-override-message: ${APP_LANDING_DEADLINE_OVERRIDE_MESSAGE:}
  sds-api:
    url: ${SDS_API_URL}
  claims-api:
    url: ${CLAIM_API_URL}
    accessToken: ${CLAIMS_API_ACCESS_TOKEN}
  upload-max-file-size: ${UPLOAD_MAX_FILE_SIZE}
  csp: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self' data:; object-src 'none'; frame-ancestors 'none'; base-uri 'self';
  submission:
    minimum-period: ${SUBMISSION_MINIMUM_PERIOD:APR-2015}
  maintenance:
    disable-at-time: ${OUTAGE_BANNER_DISABLE_AT_TIMESTAMP:2026-05-29T17:29:00Z}
    outage-banner-message: ${OUTAGE_BANNER_MESSAGE:Submit a Bulk Claim will be unavailable on Thursday 18 May between 5:00pm and 9:00pm due to planned maintenance.}

links:
  laa-homepage: https://www.gov.uk/government/organisations/legal-aid-agency
  bulk-upload-guidance: https://www.gov.uk/guidance/submit-a-bulk-claim-sabc
  bulk-upload-amendments: https://www.gov.uk/guidance/submit-a-contracted-work-and-administration-cwa-claim-online#amendments-to-claims-submitted-on-sabc

sentry:
  enabled: ${SENTRY_ENABLED:false}
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:local}
  traces-sample-rate: ${SENTRY_TRACES_SAMPLE_RATE:1}
  send-default-pii: false
  logging:
    minimum-event-level: error
    minimum-breadcrumb-level: info

feature-flags:
  is-nil-submission-enabled: ${IS_NIL_SUBMISSION_ENABLED:false}
  is-alternative-claim-view-enabled: ${IS_ALTERNATIVE_CLAIM_VIEW_ENABLED:false}
  # This updated calculated value is not available via API yet, will need to be enabled once available
  is-updated-calculated-value-available: ${IS_UPDATED_CALCULATED_VALUE_AVAILABLE:false}

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

---
spring:
  config:
    activate:
      on-profile: "!local"

# ECS structured logging
logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:info}
    org.springframework: ${SPRING_LOGGING_LEVEL:info}
    uk.gov.justice.laa.bulkclaim: ${APP_LOGGING_LEVEL:info}
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: ${spring.application.name:default}
        version: ${spring.application.version:default}
        environment: ${spring.profiles.active:default}
        node_name: ${HOSTNAME:unknown}
