spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

security:
  allowed-hosts: ""
app:
  canonical-base-url: ${"http://localhost:8080"}
  sds-api:
    url: xx

  cwa-api:
    url: xx

  claims-api:
    # This is a random UUID and does not represent a key for any service. This is to ensure that
    #  contracts created demonstrate a check for an access-token as part of a consumer request.
    access-token: e37da3d4-b8bc-4204-9528-deb6fa3bb39d
  submission:
    minimum-period: JAN-2024


links:
  laa-homepage: https://www.gov.uk/government/organisations/legal-aid-agency
  bulk-upload-spreadsheet: https://www.gov.uk/guidance/submit-a-bulk-claim-sabc#using-the-bulkload-spreadsheet-and-compatibility
  bulk-upload-guidance-documents: https://www.gov.uk/guidance/submit-a-bulk-claim-sabc#please-ensure-that-you-read-and-follow-the-steps-in-the-guidance-or-you-will-likely-encounter-errors
  bulk-upload-guidance: https://www.gov.uk/guidance/submit-a-bulk-claim-sabc
  bulk-upload-amendments: https://www.gov.uk/guidance/submit-a-contracted-work-and-administration-cwa-claim-online#amendments-to-claims-submitted-on-sabc