server:
  port: 8082
spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

management:
  server:
    port: 8182
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  canonical-base-url: "http://localhost:8080"
  sds-api:
    url: xx
  cwa-api:
    url: xx
    timeout: 1
  upload-max-file-size: 10MB
  submission:
    minimum-period: JAN-2024
  maintenance:
    disable-at-time: 2026-05-29T17:29:00Z
    outage-banner-message: Outage banner


rest-client:
  connect-timeout: 5
  read-timeout: 1

links:
  laa-homepage: https://www.gov.uk/government/organisations/legal-aid-agency
  bulk-upload-spreadsheet: https://www.gov.uk/guidance/submit-a-bulk-claim-sabc#using-the-bulkload-spreadsheet-and-compatibility
  bulk-upload-guidance-documents: https://www.gov.uk/guidance/submit-a-bulk-claim-sabc#please-ensure-that-you-read-and-follow-the-steps-in-the-guidance-or-you-will-likely-encounter-errors
  bulk-upload-guidance: https://www.gov.uk/guidance/submit-a-bulk-claim-sabc
  bulk-upload-amendments: https://www.gov.uk/guidance/submit-a-contracted-work-and-administration-cwa-claim-online#amendments-to-claims-submitted-on-sabc

feature-flags:
  is-nil-submission-enabled: true
