package uk.gov.justice.laa.bulkclaim.helper;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import uk.gov.justice.laa.dstew.payments.claimsdata.model.AreaOfLaw;
import uk.gov.justice.laa.dstew.payments.claimsdata.model.BoltOnPatch;
import uk.gov.justice.laa.dstew.payments.claimsdata.model.ClaimResponseV2;
import uk.gov.justice.laa.dstew.payments.claimsdata.model.ClaimStatus;
import uk.gov.justice.laa.dstew.payments.claimsdata.model.FeeCalculationPatch;

public final class TestObjectCreator {

  public static ClaimResponseV2 buildClaimResponseV2(AreaOfLaw areaOfLaw) {
    return ClaimResponseV2.builder()
        .id("6d10189b-b020-4cc5-891b-e53bbefa501a")
        .status(ClaimStatus.READY_TO_PROCESS)
        .areaOfLaw(areaOfLaw)
        .officeCode("0P322F")
        .dateSubmitted(OffsetDateTime.parse("2026-01-15T10:15:30+00:00"))
        .uniqueFileNumber("unique-file-number")
        .caseStartDate("2025-09-19")
        .caseConcludedDate("2026-10-20")
        .matterTypeCode("matter-type-code-one:matter-type-code-two")
        .crimeMatterTypeCode("crime-matter-type-code")
        .feeCode("fee-code")
        .representationOrderDate("2027-11-21")
        .clientForename("client-forename")
        .clientSurname("client-surname")
        .uniqueClientNumber("unique-client-number")
        .client2Forename("client-2-forename")
        .client2Surname("client-2-surname")
        .client2Ucn("client-2-ucn")
        .stageReachedCode("stage-reached-code")
        .outcomeCode("outcome-code")
        .netProfitCostsAmount(new BigDecimal("100.10"))
        .netDisbursementAmount(new BigDecimal("200.20"))
        .netCounselCostsAmount(new BigDecimal("300.30"))
        .disbursementsVatAmount(new BigDecimal("17.50"))
        .travelWaitingCostsAmount(new BigDecimal("500.50"))
        .netWaitingCostsAmount(new BigDecimal("400.40"))
        .isVatApplicable(true)
        .detentionTravelWaitingCostsAmount(new BigDecimal("700.70"))
        .jrFormFillingAmount(new BigDecimal("800.80"))
        .adjournedHearingFeeAmount(12)
        .cmrhOralCount(13)
        .cmrhTelephoneCount(14)
        .feeCalculationResponse(
            FeeCalculationPatch.builder()
                .feeCodeDescription("fee-code-description")
                .categoryOfLaw("category-of-law")
                .fixedFeeAmount(new BigDecimal("50.00"))
                .netProfitCostsAmount(new BigDecimal("110.10"))
                .disbursementAmount(new BigDecimal("210.20"))
                .disbursementVatAmount(new BigDecimal("18.50"))
                .netCostOfCounselAmount(new BigDecimal("310.30"))
                .netTravelCostsAmount(new BigDecimal("510.50"))
                .netWaitingCostsAmount(new BigDecimal("410.40"))
                .travelAndWaitingCostsAmount(new BigDecimal("920.90"))
                .detentionTravelAndWaitingCostsAmount(new BigDecimal("710.70"))
                .jrFormFillingAmount(new BigDecimal("810.80"))
                .vatIndicator(true)
                .calculatedVatAmount(new BigDecimal("25.00"))
                .totalAmount(new BigDecimal("1250.00"))
                .boltOnDetails(
                    BoltOnPatch.builder()
                        .escapeCaseFlag(true)
                        .boltOnAdjournedHearingFee(new BigDecimal("11.00"))
                        .boltOnCmrhOralFee(new BigDecimal("12.00"))
                        .boltOnCmrhTelephoneFee(new BigDecimal("13.00"))
                        .boltOnHomeOfficeInterviewFee(new BigDecimal("14.00"))
                        .boltOnSubstantiveHearingFee(new BigDecimal("15.00"))
                        .build())
                .build())
        .build();
  }

  public static ClaimResponseV2 buildClaimResponseV2() {

    return ClaimResponseV2.builder()
        .id("6d10189b-b020-4cc5-891b-e53bbefa501a")
        .status(ClaimStatus.READY_TO_PROCESS)
        .scheduleReference("schedule-reference-value")
        .lineNumber(1)
        .caseReferenceNumber("case-reference-number")
        .uniqueFileNumber("unique-file-number")
        .caseStartDate("2025-09-19")
        .caseConcludedDate("2026-10-20")
        .matterTypeCode("matter-type-code")
        .crimeMatterTypeCode("crime-matter-type-code")
        .feeSchemeCode("fee-scheme-code")
        .feeCode("fee-code")
        .procurementAreaCode("procurement-area-code")
        .accessPointCode("access-point-code")
        .deliveryLocation("delivery-location-value")
        .representationOrderDate("2027-11-21")
        .suspectsDefendantsCount(2)
        .policeStationCourtAttendancesCount(3)
        .policeStationCourtPrisonId("police-station-court-prison-id")
        .dsccNumber("dscc-number")
        .maatId("maat-id")
        .prisonLawPriorApprovalNumber("prison-law-prior-approval-number")
        .isDutySolicitor(true)
        .isYouthCourt(true)
        .schemeId("scheme-id")
        .mediationSessionsCount(4)
        .mediationTimeMinutes(5)
        .outreachLocation("outreach-location")
        .referralSource("referral-source")
        .clientForename("client-forename")
        .clientSurname("client-surname")
        .clientDateOfBirth("1995-01-01")
        .uniqueClientNumber("unique-client-number")
        .clientPostcode("client-postcode")
        .genderCode("gender-code")
        .ethnicityCode("ethnicity-code")
        .disabilityCode("disability-code")
        .isLegallyAided(true)
        .clientTypeCode("client-type-code")
        .homeOfficeClientNumber("home-office-client-number")
        .claReferenceNumber("cla-reference-number")
        .claExemptionCode("cla-exemption-code")
        .client2Forename("client-2-forename")
        .client2Surname("client-2-surname")
        .client2DateOfBirth("1999-05-02")
        .client2Ucn("client-2-ucn")
        .client2Postcode("client-2-postcode")
        .client2GenderCode("client-2-gender-code")
        .client2EthnicityCode("client-2-ethnicity-code")
        .client2DisabilityCode("client-2-disability-code")
        .client2IsLegallyAided(true)
        .caseId("case-id")
        .uniqueCaseId("unique-case-id")
        .caseStageCode("case-stage-code")
        .stageReachedCode("stage-reached-code")
        .standardFeeCategoryCode("standard-fee-category-code")
        .outcomeCode("outcome-code")
        .designatedAccreditedRepresentativeCode("designated-accredited-representative-code")
        .isPostalApplicationAccepted(true)
        .isClient2PostalApplicationAccepted(true)
        .mentalHealthTribunalReference("mental-health-tribunal-reference")
        .isNrmAdvice(true)
        .followOnWork("follow-on-work")
        .transferDate("2027-04-24")
        .exemptionCriteriaSatisfied("exemption-criteria-satisfied")
        .exceptionalCaseFundingReference("exceptional-case-funding-reference")
        .isLegacyCase(true)
        .adviceTime(6)
        .travelTime(7)
        .waitingTime(8)
        .netProfitCostsAmount(new BigDecimal("100.10"))
        .netDisbursementAmount(new BigDecimal("200.20"))
        .netCounselCostsAmount(new BigDecimal("300.30"))
        .disbursementsVatAmount(new BigDecimal("17.50"))
        .travelWaitingCostsAmount(new BigDecimal("500.50"))
        .netWaitingCostsAmount(new BigDecimal("400.40"))
        .isVatApplicable(true)
        .isToleranceApplicable(true)
        .priorAuthorityReference("prior-authority-reference")
        .isLondonRate(true)
        .adjournedHearingFeeAmount(9)
        .isAdditionalTravelPayment(true)
        .costsDamagesRecoveredAmount(new BigDecimal("600.60"))
        .meetingsAttendedCode("meetings-attended-code")
        .detentionTravelWaitingCostsAmount(new BigDecimal("700.70"))
        .jrFormFillingAmount(new BigDecimal("800.80"))
        .isEligibleClient(true)
        .courtLocationCode("court-location-code")
        .adviceTypeCode("advice-type-code")
        .medicalReportsCount(5)
        .isIrcSurgery(true)
        .surgeryDate("2017-04-23")
        .surgeryClientsCount(6)
        .surgeryMattersCount(7)
        .cmrhOralCount(1)
        .cmrhTelephoneCount(2)
        .aitHearingCentreCode("ait-hearing-centre-code")
        .isSubstantiveHearing(true)
        .hoInterview(3)
        .localAuthorityNumber("local-authority-number")
        .feeCalculationResponse(
            FeeCalculationPatch.builder()
                .boltOnDetails(BoltOnPatch.builder().escapeCaseFlag(true).build())
                .build())
        .build();
  }
}
